In [11]:
import numpy as np
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a * b
print(c)
c.shape

[[ 0.12142308 -0.90318708  0.2631064 ]
 [-0.4299514   0.31814729  0.20001232]
 [ 0.11860601 -0.01300968  0.23563337]]


(3, 3)

In [0]:
import math
def basic_sigmoid(x):
  s = 1 / (1+math.exp(-x))
  return s
  

In [11]:
import numpy as np
x = np.array([1, 2, 3])
z = np.exp(x)
print (z)

[ 2.71828183  7.3890561  20.08553692]


In [12]:
import numpy as np
x = np.array([1, 2, 3])
print(x + 3)

[4 5 6]


In [0]:
import numpy as np
def sigmoid(x):
  x = 1 / (1 + np.exp(-x))
  return x
  

In [14]:
x = np.array([1, 2, 3])
sigmoid(x)

array([0.73105858, 0.88079708, 0.95257413])

In [0]:
import numpy as np
def sigmoid_derivative(x):
  s = 1 / (1+np.exp(-x))
  ds= s*(1-s)
  return ds

In [18]:
x = np.array([1, 2, 3])
print("sigmoid_derivative(x) =  " + str(sigmoid_derivative(x)))

sigmoid_derivative(x) =  [0.19661193 0.10499359 0.04517666]


In [0]:
def image2vector(image):
  image1 = image.reshape((image.shape[0]*image.shape[1]*image.shape[2]))
  return image1

In [26]:
image = np.array([[[ 0.67826139,  0.29380381],
        [ 0.90714982,  0.52835647],
        [ 0.4215251 ,  0.45017551]],

       [[ 0.92814219,  0.96677647],
        [ 0.85304703,  0.52351845],
        [ 0.19981397,  0.27417313]],

       [[ 0.60659855,  0.00533165],
        [ 0.10820313,  0.49978937],
        [ 0.34144279,  0.94630077]]])
print("image2vector(image) = " + str(image2vector(image)))

image2vector(image) = [0.67826139 0.29380381 0.90714982 0.52835647 0.4215251  0.45017551
 0.92814219 0.96677647 0.85304703 0.52351845 0.19981397 0.27417313
 0.60659855 0.00533165 0.10820313 0.49978937 0.34144279 0.94630077]


In [0]:
def normalizerows(x):
  x_norm = np.linalg.norm(x, ord=None, axis=1, keepdims=True)
  print(x_norm.shape)
  x = x/x_norm
  return x 


In [47]:
x = np.array([[0, 3, 4], [1, 6, 4]])

print(x.shape)

normalizerows(x)
print("normalizerows(x) = " + str(normalizerows(x)))

(2, 3)
(2, 1)
(2, 1)
normalizerows(x) = [[0.         0.6        0.8       ]
 [0.13736056 0.82416338 0.54944226]]


In [0]:
import numpy as np
def softmax(x):
  x_exp = np.exp(x)
  x_sum = np.sum(x_exp, axis=1, keepdims=True)
  s = x_exp / x_sum
  return s

In [50]:
x = np.array([
    [9, 2, 5, 0, 0],
    [7, 5, 0, 0 ,0]])
print("softmax(x) = "+ str(softmax(x)))

softmax(x) = [[9.80897665e-01 8.94462891e-04 1.79657674e-02 1.21052389e-04
  1.21052389e-04]
 [8.78679856e-01 1.18916387e-01 8.01252314e-04 8.01252314e-04
  8.01252314e-04]]


In [51]:
import time

x1 = [9, 2, 5, 0, 0, 7, 5, 0, 0, 0, 9, 2, 5, 0, 0]
x2 = [9, 2, 2, 9, 0, 9, 2, 5, 0, 0, 9, 2, 5, 0, 0]

### CLASSIC DOT PRODUCT OF VECTORS IMPLEMENTATION ###
tic = time.process_time()
dot = 0
for i in range(len(x1)):
    dot+= x1[i]*x2[i]
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC OUTER PRODUCT IMPLEMENTATION ###
tic = time.process_time()
outer = np.zeros((len(x1),len(x2))) # we create a len(x1)*len(x2) matrix with only zeros
for i in range(len(x1)):
    for j in range(len(x2)):
        outer[i,j] = x1[i]*x2[j]
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC ELEMENTWISE IMPLEMENTATION ###
tic = time.process_time()
mul = np.zeros(len(x1))
for i in range(len(x1)):
    mul[i] = x1[i]*x2[i]
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

### CLASSIC GENERAL DOT PRODUCT IMPLEMENTATION ###
W = np.random.rand(3,len(x1)) # Random 3*len(x1) numpy array
tic = time.process_time()
gdot = np.zeros(W.shape[0])
for i in range(W.shape[0]):
    for j in range(len(x1)):
        gdot[i] += W[i,j]*x1[j]
toc = time.process_time()
print ("gdot = " + str(gdot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")

dot = 278
 ----- Computation time = 0.07611199999946194ms
outer = [[81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [63. 14. 14. 63.  0. 63. 14. 35.  0.  0. 63. 14. 35.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [81. 18. 18. 81.  0. 81. 18. 45.  0.  0. 81. 18. 45.  0.  0.]
 [18.  4.  4. 18.  0. 18.  4. 10.  0.  0. 18.  4. 10.  0.  0.]
 [45. 10. 10. 45.  0. 45. 10. 25.  0.  0. 45. 10. 25.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0

In [53]:
x1 = [9, 2]
x2 = [9, 2]

### VECTORIZED DOT PRODUCT OF VECTORS ###
tic = time.process_time()
dot = np.dot(x1,x2)
toc = time.process_time()
print ("dot = " + str(dot) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")
print(dot)

dot = 85
 ----- Computation time = 1.0170020000010993ms
85


In [54]:
### VECTORIZED OUTER PRODUCT ###
tic = time.process_time()
outer = np.outer(x1,x2)
toc = time.process_time()
print ("outer = " + str(outer) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")
print(outer)

outer = [[81 18]
 [18  4]]
 ----- Computation time = 0.184815000000782ms
[[81 18]
 [18  4]]


In [55]:
### VECTORIZED ELEMENTWISE MULTIPLICATION ###
tic = time.process_time()
mul = np.multiply(x1,x2)
toc = time.process_time()
print ("elementwise multiplication = " + str(mul) + "\n ----- Computation time = " + str(1000*(toc - tic)) + "ms")
print(mul)

elementwise multiplication = [81  4]
 ----- Computation time = 0.07045699999963517ms
[81  4]


In [0]:
import numpy as np
def L1(yhat, y):
  L1 = np.sum(y - yhat)
  return L1

In [61]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L1 = " + str(L1(yhat,y)))

L1 = 0.4999999999999999


In [0]:
def L2(yhat, y):
  
  loss1 = np.dot((yhat - y), (yhat - y))
  return loss1

In [88]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y = np.array([1, 0, 0, 1, 1])
print("L2 = " + str(L2(yhat,y)))

L2 = 0.43
